### ISSUE TITLE
BUG: update fails if using HTTP protocol (instead of HTTPS)

### ISSUE THREAD

**Issue by S-trace** [omnirom/android_packages_apps_OpenDelta#24]
This bug was invented by commit https://github.com/omnirom/android_packages_apps_OpenDelta/commit/64545998037f363f2b35cc7f90514312fbd8399e
Slightly patched OpenDelta: 
```
diff --git a/src/eu/chainfire/opendelta/UpdateService.java b/src/eu/chainfire/opendelta/UpdateService.java
index ec6f612..0ae2b27 100644
--- a/src/eu/chainfire/opendelta/UpdateService.java
+++ b/src/eu/chainfire/opendelta/UpdateService.java
@@ -564,6 +564,7 @@ OnWantUpdateCheckListener, OnSharedPreferenceChangeListener {
             return urlConnection;
         } catch (Exception e) {
             Logger.i("Failed to connect to server");
+            Logger.ex(e);
             return null;
         }
     }
```
And got following error in logcat:
```
03-22 21:27:42.574  2134  2150 I OpenDelta: Failed to connect to server
03-22 21:27:42.574  2134  2150 W System.err: java.lang.ClassCastException: com.android.okhttp.internal.huc.HttpURLConnectionImpl cannot be cast to javax.net.ssl.HttpsURLConnection
03-22 21:27:42.574  2134  2150 W System.err:    at eu.chainfire.opendelta.UpdateService.setupHttpsRequest(UpdateService.java:553)
03-22 21:27:42.574  2134  2150 W System.err:    at eu.chainfire.opendelta.UpdateService.downloadUrlMemoryAsString(UpdateService.java:612)
03-22 21:27:42.574  2134  2150 W System.err:    at eu.chainfire.opendelta.UpdateService.getNewestFullBuild(UpdateService.java:858)
03-22 21:27:42.575  2134  2150 W System.err:    at eu.chainfire.opendelta.UpdateService.-wrap8(UpdateService.java)
03-22 21:27:42.575  2134  2150 W System.err:    at eu.chainfire.opendelta.UpdateService$5.run(UpdateService.java:1845)
03-22 21:27:42.575  2134  2150 W System.err:    at android.os.Handler.handleCallback(Handler.java:739)
03-22 21:27:42.575  2134  2150 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
03-22 21:27:42.575  2134  2150 W System.err:    at android.os.Looper.loop(Looper.java:148)
03-22 21:27:42.575  2134  2150 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:61)
```
HTTP server works fine after reverting commit 64545998

Is it possible to fix this? Or OpenDelta works as designed?

Thank you.

**Comment by Lrs121** [comment]
Check out the comments in this code review [https://gerrit.omnirom.org/#/c/17181/](https://gerrit.omnirom.org/#/c/17181/)

**Comment by maxwen** [comment]
Only https is supported
