### ISSUE TITLE
zipadjust and files < 2G

### ISSUE THREAD

**Issue by mTresk** [omnirom/android_packages_apps_OpenDelta#29]
zipadjust show size of files larger then 2G in negative value.
`system.new.dat (-1696239616 --> 1331883296) [E849E40D] (0)`
It shows -1696239616 but it shoud be 2696239616
This leads to an error in minsignapk.jar
```
java.lang.NegativeArraySizeException
	at eu.chainfire.minsignapk.MinSignAPK.main(MinSignAPK.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
```

**Comment by DerTeufel** [comment]
The issue is the use of int to retrieve the filesize for example.
After I updated zipadjust, dedelta still failed... :(
